<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Capitulo', 'doctrine');

/**
 * BaseCapitulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idEpisodio
 * @property string $titulo
 * @property text $descripcion
 * @property boolean $soloAccesoPremium
 * @property boolean $soloAccesoLogado
 * @property boolean $borrado
 * @property boolean $activo
 * @property Episodio $Episodio
 * @property Doctrine_Collection $VideoCapitulo
 * @property Doctrine_Collection $FotografiaCapitulo
 * 
 * @method integer             getIdEpisodio()         Returns the current record's "idEpisodio" value
 * @method string              getTitulo()             Returns the current record's "titulo" value
 * @method text                getDescripcion()        Returns the current record's "descripcion" value
 * @method boolean             getSoloAccesoPremium()  Returns the current record's "soloAccesoPremium" value
 * @method boolean             getSoloAccesoLogado()   Returns the current record's "soloAccesoLogado" value
 * @method boolean             getBorrado()            Returns the current record's "borrado" value
 * @method boolean             getActivo()             Returns the current record's "activo" value
 * @method Episodio            getEpisodio()           Returns the current record's "Episodio" value
 * @method Doctrine_Collection getVideoCapitulo()      Returns the current record's "VideoCapitulo" collection
 * @method Doctrine_Collection getFotografiaCapitulo() Returns the current record's "FotografiaCapitulo" collection
 * @method Capitulo            setIdEpisodio()         Sets the current record's "idEpisodio" value
 * @method Capitulo            setTitulo()             Sets the current record's "titulo" value
 * @method Capitulo            setDescripcion()        Sets the current record's "descripcion" value
 * @method Capitulo            setSoloAccesoPremium()  Sets the current record's "soloAccesoPremium" value
 * @method Capitulo            setSoloAccesoLogado()   Sets the current record's "soloAccesoLogado" value
 * @method Capitulo            setBorrado()            Sets the current record's "borrado" value
 * @method Capitulo            setActivo()             Sets the current record's "activo" value
 * @method Capitulo            setEpisodio()           Sets the current record's "Episodio" value
 * @method Capitulo            setVideoCapitulo()      Sets the current record's "VideoCapitulo" collection
 * @method Capitulo            setFotografiaCapitulo() Sets the current record's "FotografiaCapitulo" collection
 * 
 * @package    amina
 * @subpackage model
 * @author     Allel software
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCapitulo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('capitulo');
        $this->hasColumn('idEpisodio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('titulo', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('soloAccesoPremium', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('soloAccesoLogado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '1',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Episodio', array(
             'local' => 'idEpisodio',
             'foreign' => 'id'));

        $this->hasMany('VideoCapitulo', array(
             'local' => 'id',
             'foreign' => 'idCapitulo'));

        $this->hasMany('FotografiaCapitulo', array(
             'local' => 'id',
             'foreign' => 'idCapitulo'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}