<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProgramaColegio', 'doctrine');

/**
 * BaseProgramaColegio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property text $descripcion
 * @property boolean $soloAccesoPremium
 * @property boolean $soloAccesoLogado
 * @property boolean $borrado
 * @property boolean $activo
 * @property Doctrine_Collection $FotografiaProgramaColegio
 * 
 * @method string              getTitulo()                    Returns the current record's "titulo" value
 * @method text                getDescripcion()               Returns the current record's "descripcion" value
 * @method boolean             getSoloAccesoPremium()         Returns the current record's "soloAccesoPremium" value
 * @method boolean             getSoloAccesoLogado()          Returns the current record's "soloAccesoLogado" value
 * @method boolean             getBorrado()                   Returns the current record's "borrado" value
 * @method boolean             getActivo()                    Returns the current record's "activo" value
 * @method Doctrine_Collection getFotografiaProgramaColegio() Returns the current record's "FotografiaProgramaColegio" collection
 * @method ProgramaColegio     setTitulo()                    Sets the current record's "titulo" value
 * @method ProgramaColegio     setDescripcion()               Sets the current record's "descripcion" value
 * @method ProgramaColegio     setSoloAccesoPremium()         Sets the current record's "soloAccesoPremium" value
 * @method ProgramaColegio     setSoloAccesoLogado()          Sets the current record's "soloAccesoLogado" value
 * @method ProgramaColegio     setBorrado()                   Sets the current record's "borrado" value
 * @method ProgramaColegio     setActivo()                    Sets the current record's "activo" value
 * @method ProgramaColegio     setFotografiaProgramaColegio() Sets the current record's "FotografiaProgramaColegio" collection
 * 
 * @package    amina
 * @subpackage model
 * @author     Allel software
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProgramaColegio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('programaColegio');
        $this->hasColumn('titulo', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('soloAccesoPremium', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('soloAccesoLogado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '1',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FotografiaProgramaColegio', array(
             'local' => 'id',
             'foreign' => 'idProgramaColegio'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}