<?php

/**
 * CapituloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CapituloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CapituloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Capitulo');
    }
}