<?php

/**
 * ElExpertoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElExpertoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElExpertoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ElExperto');
    }
}