<?php

/**
 * ProgramaColegioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProgramaColegioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProgramaColegioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProgramaColegio');
    }
}