<?php

/**
 * Capitulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    amina
 * @subpackage model
 * @author     Allel software
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Capitulo extends BaseCapitulo
{
}
