<?php

/**
 * EpisodioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EpisodioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EpisodioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Episodio');
    }
}