<?php

/**
 * FotografiaCapituloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaCapituloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaCapituloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaCapitulo');
    }
}