<?php

/**
 * FotografiaContenidoPadresYProfesoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaContenidoPadresYProfesoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaContenidoPadresYProfesoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaContenidoPadresYProfesores');
    }
}