<?php

/**
 * FotografiaProgramaColegioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaProgramaColegioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaProgramaColegioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaProgramaColegio');
    }
}