<?php

/**
 * JuegoEpisodioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JuegoEpisodioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JuegoEpisodioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JuegoEpisodio');
    }
}