<?php

/**
 * UnidadTematicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadTematicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadTematicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadTematica');
    }
}