<?php

/**
 * VideoContenidoPadresYProfesoresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoContenidoPadresYProfesoresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoContenidoPadresYProfesoresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoContenidoPadresYProfesores');
    }
}